package ois.cc.gravity.framework.events;


public enum EventType
{
    /**
     * Events generated by Framework.
     */
    Framework(0),
    /**
     * Acknowledges the request received.
     */
    Ack(100),
    /**
     * For async events where server would pass some info back to client.
     */
    Info(180),
    /**
     * For agent status.
     */
    Stats(181),
    /**
     * Asynchronous Telephony Events.
     */
    TEvent(191),
    /**
     * Asynchronous Email Events.
     */
    EmEvent(192),
    /**
     * Asynchronous Chat Events.
     */
    ChEvent(193),

    /**
     * Asynchronous Video Events.
     */
    VdEvent(194),

    /**
     * Request processing success.
     */
    Success(200),
    /**
     * Indicates that this event is a result of failure during processing the request.
     */
    Failed(400),
    /**
     * Server internal error or exception while processing the request. This will mostly cater to un-handled scenarios.
     */
    Error(500),;

    private int code;

    private EventType()
    {

    }

    private EventType(int code)
    {
        this.code = code;
    }

    public int Code()
    {
        return code;
    }

    public String Name()
    {
        return this.name();
    }
}

